//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimTrixx.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public string SimtrixxUserId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    }
}
